Name: upgrade.api
Host: 0.0.0.0
Port: 8181
Timeout: 100000

Auth:
  AccessSecret: 1S6VKDtsJf3z1n2VKDtsJf3z # the same as core
  AccessExpire: 259200

CROSConf:
  Address: '*'

Log:
  ServiceName: upgradeApiLogger
  Mode: file
  Path: ./logs/upgrade/api
  Level: info
  Compress: false
  Encoding: json
  KeepDays: 7
  StackCoolDownMillis: 100

DatabaseConf:
  Type: mysql
  Host: upgradelink-mysql
  Port: 3306
  DBName: upgrade
  Username: root # set your username
  Password: Rootroot123! # set your password
  MaxOpenConn: 100
  SSLMode: disable # disable or require
  CacheTime: 5
  MysqlConfig: "&loc=Asia%2FShanghai"

CoreRpc:
  Target: upgradelink-admin-core-rpc:9101
  Enabled: true

RedisConf:
  Host: upgradelink-redis:6379
  Db: 0
  Pass: a123456

CasbinDatabaseConf:
  Type: mysql
  Host: upgradelink-mysql
  Port: 3306
  DBName: upgrade
  Username: root # set your username
  Password: Rootroot123! # set your password
  MaxOpenConn: 100
  SSLMode: disable # disable or require
  CacheTime: 5
  MysqlConfig: "&loc=Asia%2FShanghai"

CasbinConf:
  ModelText: |
    [request_definition]
    r = sub, obj, act
    [policy_definition]
    p = sub, obj, act
    [role_definition]
    g = _, _
    [policy_effect]
    e = some(where (p.eft == allow))
    [matchers]
    m = r.sub == p.sub && keyMatch2(r.obj,p.obj) && r.act == p.act

I18nConf:
  Dir: # set the path of locale if you need to load files