Name: mcms.rpc
ListenOn: 0.0.0.0:9106
Timeout: 5000

DatabaseConf:
  Type: mysql
  Host: upgrade-mysql
  Port: 3306
  DBName: upgrade
  Username: root # set your username
  Password: Rootroot123! # set your password
  MaxOpenConn: 100
  SSLMode: disable # disable or require
  CacheTime: 5
  MysqlConfig: "&loc=Asia%2FShanghai"

RedisConf:
  Host: upgrade-redis:6379
  Db: 0
  Pass: a123456

Log:
  ServiceName: mcmsRpcLogger
  Mode: file
  Path: ./logs/mcms/rpc
  Encoding: json
  Level: info
  Compress: false
  KeepDays: 7
  StackCoolDownMillis: 100

Prometheus:
  Host: 0.0.0.0
  Port: 4006
  Path: /metrics